In [42]:
import pandas as pd
a = pd.read_csv("./data/animal_infra.csv", index_col=0)

In [44]:
del a['Unnamed: 0.1']
a

,name,lat,lng,address,type
0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원
1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원
2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원
3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원
4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원
...,...,...,...,...,...
1051,에코앤세이브,37.531417,126.780113,경기 부천시 산업로7번길 73,반려동물용품점
1052,도그싸롱,37.575132,126.811453,서울 강서구 금낭화로17길 3,반려동물용품점
1053,라니펫,37.503062,126.901044,서울 서대문구 남가좌동 277-2,반려동물용품점
1054,펫랜드 부천점,37.510863,126.775415,경기 부천시 도약로 239,반려동물용품점
1055,펫블라썸,37.525178,126.924877,서울 은평구 응암동 126-21 B102호,반려동물용품점

In [15]:
# pd.set_option('display.max_rows', None) # 전체행 출력해주는 설정명령어
pd.reset_option('display.max_rows', None) # 원래 설정으로

In [45]:
a = a[~a['type'].str.contains('동물보호센터')]
a = a[~a['type'].str.contains('동물장묘업')]
a = a[~a['type'].str.contains('동물용의료용구판매업')]
a

,name,lat,lng,address,type
0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원
1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원
2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원
3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원
4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원
...,...,...,...,...,...
1051,에코앤세이브,37.531417,126.780113,경기 부천시 산업로7번길 73,반려동물용품점
1052,도그싸롱,37.575132,126.811453,서울 강서구 금낭화로17길 3,반려동물용품점
1053,라니펫,37.503062,126.901044,서울 서대문구 남가좌동 277-2,반려동물용품점
1054,펫랜드 부천점,37.510863,126.775415,경기 부천시 도약로 239,반려동물용품점
1055,펫블라썸,37.525178,126.924877,서울 은평구 응암동 126-21 B102호,반려동물용품점

In [46]:
hos = a[a['type'] == '동물병원']
petpharmacy = a[a['type'] == '동물약국업']
petplay = a[a['type'] == '동물놀이터']
petpark = a[a['type'] == '동물공원']
동물동반식당 = a[a['type'] == '동물동반식당']
동물동반카페 = a[a['type'] == '동물동반카페']
petbeauty = a[a['type'] == '동물미용업']
pettaxi = a[a['type'] == '동물운송업']
반려동물용품점 = a[a['type'] == '반려동물용품점']
petsell = a[a['type'] == '동물판매업']
feedmake = a[a['type'] == '사료제조업']
위탁관리 = a[a['type'] == '위탁관리업']

In [47]:
hos['type_id'] = '1'
petpharmacy['type_id'] = '2'
petplay['type_id'] = '3'
petpark['type_id'] = '4'
동물동반식당['type_id'] = '5'
동물동반카페['type_id'] = '6'
petbeauty['type_id'] = '7'
pettaxi['type_id'] = '8'
반려동물용품점['type_id'] = '9'
petsell['type_id'] = '10'
feedmake['type_id'] = '11'
위탁관리['type_id'] = '12'

<ipython-input-47-8160cfe1ce80>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hos['type_id'] = '1'
<ipython-input-47-8160cfe1ce80>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  petpharmacy['type_id'] = '2'
<ipython-input-47-8160cfe1ce80>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  petplay['type_id'] = '3'
<ipython-input-47-8160cfe1ce80>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  petpark['type_id'] = '4'
<ipython-input-47-8160cfe1ce80>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  동물동반식당['type_id'] = '5'
<ipython-input-47-8160cfe1ce80>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  동물동반카페['type_id'] = '6'
<ipython-input-47-8160cfe1ce80>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  petbeauty['type_id'] = '7'
<ipython-input-47-8160cfe1ce80>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pettaxi['type_id'] = '8'
<ipython-input-47-8160cfe1ce80>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  반려동물용품점['type_id'] = '9'
<ipython-input-47-8160cfe1ce80>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  petsell['type_id'] = '10'
<ipython-input-47-8160cfe1ce80>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feedmake['type_id'] = '11'
<ipython-input-47-8160cfe1ce80>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  위탁관리['type_id'] = '12'

In [48]:
result = pd.concat([hos, petpharmacy, petplay, petpark, 동물동반식당,동물동반카페, petbeauty, pettaxi, 
                    반려동물용품점, petsell, feedmake, 위탁관리])
result

,name,lat,lng,address,type,type_id
0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원,1
1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원,1
2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원,1
3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원,1
4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원,1
...,...,...,...,...,...,...
2469,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,위탁관리업,12
2470,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,위탁관리업,12
2471,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,위탁관리업,12
2472,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,위탁관리업,12
2473,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,위탁관리업,12

In [49]:
del result['type']
result

,name,lat,lng,address,type_id
0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),1
1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),1
2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),1
3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),1
4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),1
...,...,...,...,...,...
2469,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,12
2470,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,12
2471,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,12
2472,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,12
2473,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,12

In [50]:
# 저장
result.to_csv('./data/typeid_fin.csv')

In [2]:
import pandas as pd
a = pd.read_csv("./data/typeid_fin.csv", index_col=0)

In [3]:
a

,name,lat,lng,address,type,type_id
0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원,1
1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원,1
2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원,1
3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원,1
4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원,1
...,...,...,...,...,...,...
2469,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,위탁관리업,12
2470,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,위탁관리업,12
2471,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,위탁관리업,12
2472,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,위탁관리업,12
2473,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,위탁관리업,12

In [7]:
# 인덱싱
a.index=range(0,len(a))
a

,name,lat,lng,address,type,type_id
0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원,1
1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원,1
2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원,1
3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원,1
4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원,1
...,...,...,...,...,...,...
15343,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,위탁관리업,12
15344,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,위탁관리업,12
15345,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,위탁관리업,12
15346,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,위탁관리업,12
15347,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,위탁관리업,12

In [8]:
a = a.reset_index()
# a = a.drop(["index"], axis=1)
a

,index,name,lat,lng,address,type,type_id
0,0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원,1
1,1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원,1
2,2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원,1
3,3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원,1
4,4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원,1
...,...,...,...,...,...,...,...
15343,15343,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,위탁관리업,12
15344,15344,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,위탁관리업,12
15345,15345,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,위탁관리업,12
15346,15346,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,위탁관리업,12
15347,15347,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,위탁관리업,12

In [1]:
# for i in a.index:
#    print('infra_' + range(0,15348))

In [2]:
# for i in a['index']:
#     i == range(1,15348)
#     a['index']

In [11]:
a

,index,name,lat,lng,address,type,type_id
0,0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원,1
1,1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원,1
2,2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원,1
3,3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원,1
4,4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원,1
...,...,...,...,...,...,...,...
15343,15343,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,위탁관리업,12
15344,15344,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,위탁관리업,12
15345,15345,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,위탁관리업,12
15346,15346,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,위탁관리업,12
15347,15347,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,위탁관리업,12

In [13]:
# 저장
a.to_csv('./data/typeid_fin.csv')

In [10]:
import pandas as pd
a = pd.read_csv("./data/typeid_fin.csv", index_col=0)

In [13]:
a

,index,name,lat,lng,address,type,type_id
0,0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원,1
1,1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원,1
2,2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원,1
3,3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원,1
4,4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원,1
...,...,...,...,...,...,...,...
15343,15343,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,위탁관리업,12
15344,15344,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,위탁관리업,12
15345,15345,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,위탁관리업,12
15346,15346,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,위탁관리업,12
15347,15347,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,위탁관리업,12

In [14]:
a.rename(columns = {'index' : 'infra_id'}, inplace= True)
a

,infra_id,name,lat,lng,address,type,type_id
0,0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),동물병원,1
1,1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),동물병원,1
2,2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),동물병원,1
3,3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),동물병원,1
4,4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),동물병원,1
...,...,...,...,...,...,...,...
15343,15343,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,위탁관리업,12
15344,15344,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,위탁관리업,12
15345,15345,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,위탁관리업,12
15346,15346,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,위탁관리업,12
15347,15347,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,위탁관리업,12

In [15]:
del a['type']
a

,infra_id,name,lat,lng,address,type_id
0,0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),1
1,1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),1
2,2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),1
3,3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),1
4,4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),1
...,...,...,...,...,...,...
15343,15343,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,12
15344,15344,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,12
15345,15345,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,12
15346,15346,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,12
15347,15347,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,12

In [16]:
a.index=a.index+1
a

,infra_id,name,lat,lng,address,type_id
1,0,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),1
2,1,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),1
3,2,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),1
4,3,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),1
5,4,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),1
...,...,...,...,...,...,...
15344,15343,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,12
15345,15344,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,12
15346,15345,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,12
15347,15346,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,12
15348,15347,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,12

In [18]:
a.reset_index(inplace=True)
del a['infra_id']

In [20]:
a.rename(columns = {'index' : 'infra_id'}, inplace= True)
a

,infra_id,name,lat,lng,address,type_id
0,1,더조은 동물의료센터,37.449517,126.903311,서울특별시 금천구 시흥대로 172 서우빌딩 (시흥동),1
1,2,광진동물의료센터,37.545253,127.085949,서울특별시 광진구 광나루로 507 (구의동),1
2,3,놀로동물행동클리닉,37.519441,127.049030,서울특별시 강남구 삼성로133길 7 베디베로스퀘어 5층 (청담동),1
3,4,현대종합동물병원,37.664403,127.042060,서울특별시 도봉구 도봉로 669 1층 (방학동),1
4,5,홍익동물종합병원,37.548097,126.918386,서울특별시 마포구 독막로 45 (합정동),1
...,...,...,...,...,...,...
15343,15344,몽이슈반려동물미용,37.475617,126.852392,경기도 광명시 광명로 855-1 3층,12
15344,15345,아름다울개반려동물미용,37.470397,126.856084,경기도 광명시 도덕로 79 3층,12
15345,15346,몽몽바블펫샵반려동물미용,37.519515,126.856562,서울특별시 양천구 중앙로36길 24,12
15346,15347,포독반려동물미용,37.559003,126.834321,서울특별시 강서구 마곡동로10길 46 406호,12
15347,15348,댕댕당반려동물미용,37.614741,126.833169,경기도 고양시 덕양구 무원로6번길 61 GL프라자 3층,12

In [21]:
# 저장
a.to_csv('./data/typeid_fin.csv')

In [27]:
a = pd.read_csv("./data/typeid_fin.csv", index_col=0, encoding='UTF-8')
a

,infra_id,name,lat,lng,address,type_id,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,?붿“? ?숇Ъ?섎즺?쇳꽣,37.44951674,126.9033108,?쒖슱?밸퀎??湲덉쿇援??쒗씎?濡?172 ?쒖슦鍮뚮뵫 (?쒗씎??,1,NaN,NaN,NaN,NaN
1,2,愿묒쭊?숇Ъ?섎즺?쇳꽣,37.54525344,127.0859485,?쒖슱?밸퀎??愿묒쭊援?愿묐굹猷⑤줈 507 (援ъ쓽??,1,NaN,NaN,NaN,NaN
2,3,?濡쒕룞臾쇳뻾?숉겢由щ땳,37.51944086,127.0490301,?쒖슱?밸퀎??媛뺣궓援??쇱꽦濡?33湲?7 踰좊뵒踰좊줈?ㅽ섏뼱 5痢?(泥?떞??,1,NaN,NaN,NaN,NaN
3,4,?꾨?醫낇빀?숇Ъ蹂묒썝,37.66440307,127.0420598,?쒖슱?밸퀎???꾨큺援??꾨큺濡?669 1痢?(諛⑺븰??,1,NaN,NaN,NaN,NaN
4,5,?띿씡?숇Ъ醫낇빀蹂묒썝,37.5480971,126.9183856,?쒖슱?밸퀎??留덊룷援??낅쭑濡?45 (?⑹젙??,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
15343,15344,紐쎌씠?덈컲?ㅻ룞臾쇰???37.4756175,126.8523921,寃쎄린??愿묐챸??愿묐챸濡?855-1 3痢?12,NaN,NaN,NaN,NaN,NaN,NaN
15344,15345,?꾨쫫?ㅼ슱媛쒕컲?ㅻ룞臾쇰???37.4703975,126.8560839,寃쎄린??愿묐챸???꾨뜒濡?79 3痢?12,NaN,NaN,NaN,NaN,NaN,NaN
15345,15346,紐쎈そ諛붾툝?レ꺏諛섎젮?숇Ъ誘몄슜,37.519515,126.8565618,?쒖슱?밸퀎???묒쿇援?以묒븰濡?6湲?24,12,NaN,NaN,NaN,NaN
15346,15347,?щ룆諛섎젮?숇Ъ誘몄슜,37.5590032,126.8343207,?쒖슱?밸퀎??媛뺤꽌援?留덇끝?숇줈10湲?46 406??12,NaN,NaN,NaN,NaN,NaN
15347,15348,?뺣뙐?밸컲?ㅻ룞臾쇰???37.6147407,126.8331688,寃쎄린??怨좎뼇???뺤뼇援?臾댁썝濡?踰덇만 61 GL?꾨씪??3痢?12,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
del a['Unnamed: 7']
del a['Unnamed: 8']
del a['Unnamed: 9']
del a['Unnamed: 10']

In [29]:
a

,infra_id,name,lat,lng,address,type_id
0,1,?붿“? ?숇Ъ?섎즺?쇳꽣,37.44951674,126.9033108,?쒖슱?밸퀎??湲덉쿇援??쒗씎?濡?172 ?쒖슦鍮뚮뵫 (?쒗씎??,1
1,2,愿묒쭊?숇Ъ?섎즺?쇳꽣,37.54525344,127.0859485,?쒖슱?밸퀎??愿묒쭊援?愿묐굹猷⑤줈 507 (援ъ쓽??,1
2,3,?濡쒕룞臾쇳뻾?숉겢由щ땳,37.51944086,127.0490301,?쒖슱?밸퀎??媛뺣궓援??쇱꽦濡?33湲?7 踰좊뵒踰좊줈?ㅽ섏뼱 5痢?(泥?떞??,1
3,4,?꾨?醫낇빀?숇Ъ蹂묒썝,37.66440307,127.0420598,?쒖슱?밸퀎???꾨큺援??꾨큺濡?669 1痢?(諛⑺븰??,1
4,5,?띿씡?숇Ъ醫낇빀蹂묒썝,37.5480971,126.9183856,?쒖슱?밸퀎??留덊룷援??낅쭑濡?45 (?⑹젙??,1
...,...,...,...,...,...,...
15343,15344,紐쎌씠?덈컲?ㅻ룞臾쇰???37.4756175,126.8523921,寃쎄린??愿묐챸??愿묐챸濡?855-1 3痢?12,NaN,NaN
15344,15345,?꾨쫫?ㅼ슱媛쒕컲?ㅻ룞臾쇰???37.4703975,126.8560839,寃쎄린??愿묐챸???꾨뜒濡?79 3痢?12,NaN,NaN
15345,15346,紐쎈そ諛붾툝?レ꺏諛섎젮?숇Ъ誘몄슜,37.519515,126.8565618,?쒖슱?밸퀎???묒쿇援?以묒븰濡?6湲?24,12
15346,15347,?щ룆諛섎젮?숇Ъ誘몄슜,37.5590032,126.8343207,?쒖슱?밸퀎??媛뺤꽌援?留덇끝?숇줈10湲?46 406??12,NaN
15347,15348,?뺣뙐?밸컲?ㅻ룞臾쇰???37.6147407,126.8331688,寃쎄린??怨좎뼇???뺤뼇援?臾댁썝濡?踰덇만 61 GL?꾨씪??3痢?12,NaN,NaN

In [40]:
a = pd.read_csv("./data/typeid_fin.csv", index_col=0, encoding='euc-kr')
a

,infra_id,name,lat,lng,address,type_id,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,?�조?� ?�물?�료?�터,37.44951674,126.9033108,?�울?�별??금천�??�흥?��?172 ?�우빌딩 (?�흥??,1,NaN,NaN,NaN,NaN
1,2,광진?�물?�료?�터,37.54525344,127.0859485,?�울?�별??광진�?광나루로 507 (구의??,1,NaN,NaN,NaN,NaN
2,3,?�로동물행?�클리닉,37.51944086,127.0490301,?�울?�별??강남�??�성�?33�?7 베디베로?�퀘어 5�?(�?��??,1,NaN,NaN,NaN,NaN
3,4,?��?종합?�물병원,37.66440307,127.0420598,?�울?�별???�봉�??�봉�?669 1�?(방학??,1,NaN,NaN,NaN,NaN
4,5,?�익?�물종합병원,37.5480971,126.9183856,?�울?�별??마포�??�막�?45 (?�정??,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
15343,15344,몽이?�반?�동물�???37.4756175,126.8523921,경기??광명??광명�?855-1 3�?12,NaN,NaN,NaN,NaN,NaN,NaN
15344,15345,?�름?�울개반?�동물�???37.4703975,126.8560839,경기??광명???�덕�?79 3�?12,NaN,NaN,NaN,NaN,NaN,NaN
15345,15346,몽몽바블?�샵반려?�물미용,37.519515,126.8565618,?�울?�별???�천�?중앙�?6�?24,12,NaN,NaN,NaN,NaN
15346,15347,?�독반려?�물미용,37.5590032,126.8343207,?�울?�별??강서�?마곡?�로10�?46 406??12,NaN,NaN,NaN,NaN,NaN
15347,15348,?�댕?�반?�동물�???37.6147407,126.8331688,경기??고양???�양�?무원�?번길 61 GL?�라??3�?12,NaN,NaN,NaN,NaN,NaN,NaN